### PR TITLE
Ported to sugar3.speech

### LINKED ISSUE #7: Port to sugar3.speech
Activity embeds own speech instance; this may be replaced with the sugar-toolkit-gtk3 speech instance.

### PR DESCRIPTION
**Pull request by sanatankc**
closes #7

### CODE REVIEW

**Comment by walterbender** [comment]
I get a KeyError: 'en_gb-x-rp'
Maybe my configuration is incorrect, but should we check in any case and use a default voice?

**Comment by sanatankc** [comment]
Is it working fine from your end?

**Comment by walterbender** [comment]
Works now. Could you please clean up the pep8 errors (a few lines too long)

**Comment by sanatankc** [comment]
Done, except those modules pep8 errors.

**Pull request merged**
